### PR TITLE
Change 'Homework' to 'Assignment' in sidebar menu.

### PR DESCRIPTION
**Pull request by spark008**

### CODE REVIEW

**Comment by pwnall** [comment]
Thank you!

**Comment by StaphanyPaper** [comment]
All your roommates graduated, you are still here! @pwnall

**Comment by StaphanyPaper** [comment]
Pig opens her legs again!!! @spark008

**Comment by StaphanyPaper** [comment]
Awesome pig prevents Victor from graduation!!! @pwnall

**Comment by StaphanyPaper** [comment]
Pig starts prostitution again!!! @spark008

**Pull request merged**
